"""Add OAuth fields to User model

Revision ID: 9989a8e6d158
Revises: 8d30e311de91
Create Date: 2025-06-15 10:27:00.985598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9989a8e6d158'
down_revision = '8d30e311de91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('oauth_id', sa.String(length=100), nullable=True))
        batch_op.drop_constraint(batch_op.f('users_github_id_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('users_google_id_key'), type_='unique')
        batch_op.drop_column('google_id')
        batch_op.drop_column('github_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('google_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('users_google_id_key'), ['google_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('users_github_id_key'), ['github_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('oauth_id')
        batch_op.drop_column('oauth_provider')

    # ### end Alembic commands ###
